version: "3.8"
services:

  mysqldb:
    image: mysql:5.7
    container_name: mysql_db
    restart: unless-stopped

    env_file: .env
    environment:
      - MYSQL_ROOT_USER=$MYSQLDB_USER
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    command: --init-file /data/application/init.sql
    volumes:
       - ./auth-service/src/docker/data/init.sql:/data/application/init.sql
    networks:
      my_app:
        aliases:
          - "mysqldb"

  gateway_service:
    container_name: gateway-service
    depends_on:
      - mysqldb
    build: ./gateway-service/
    restart: on-failure
    env_file: .env
    ports:
      - $GATEWAY_LOCAL_PORT:$GATEWAY_DOCKER_PORT
    networks:
      - my_app

  auth_service:
    container_name: auth-service
    depends_on:
        - gateway_service
    build: ./auth-service/
    restart: on-failure
    env_file: .env
    ports:
        - $AUTH_LOCAL_PORT:$AUTH_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    networks:
      - my_app

  core_service:
    container_name: core-service
    depends_on:
      - gateway_service
    build: ./core-service/
    restart: on-failure
    env_file: .env
    ports:
      - $CORE_LOCAL_PORT:$CORE_DOCKER_PORT
    networks:
      - my_app

networks:
  my_app:
    driver: "bridge"