CREATE TABLE groups
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title           VARCHAR(255),
    teacher_user_id BIGINT,
    CONSTRAINT pk_groups PRIMARY KEY (id)
);

ALTER TABLE groups
    ADD CONSTRAINT FK_GROUPS_ON_TEACHER_USER FOREIGN KEY (teacher_user_id) REFERENCES persons (user_id);