CREATE TABLE groups
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title           VARCHAR(255),
    CONSTRAINT pk_groups PRIMARY KEY (id)
);

create table group_students_teachers
(
    group_id bigint not null
constraint fk_group_students_teachers_on_group references groups(id),
student_id bigint not null ,
teacher_id bigint not null
);

insert into groups (id, title)
values  (1, 'JAVA-2022'),
        (2, 'JAVA-2021'),
        (3, 'JAVA-2020');

insert into group_students_teachers (group_id, student_id, teacher_id)
values  (1, 1, 2),
        (1, 10, 20),
        (2, 11, 21),
        (2, 12, 22),
        (3, 15, 24),
        (3, 19, 27);