CREATE TABLE lessonTemplates
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    theme    VARCHAR(255),
    duration TIME WITHOUT TIME ZONE,
    CONSTRAINT pk_lessons PRIMARY KEY (id)
);

insert into lessonTemplates(id, theme, duration)
values (1,'Math1','00:45:00'),
       (2,'Math2','00:45:00'),
       (3,'Math3','00:45:00'),
       (4,'Math4','00:45:00'),
       (5,'Math5','00:45:00');