CREATE TABLE faculties
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title                 VARCHAR(255),
    learning_programme_id BIGINT,
    CONSTRAINT pk_faculties PRIMARY KEY (id)
);

ALTER TABLE faculties
    ADD CONSTRAINT FK_FACULTIES_ON_LEARNINGPROGRAMME FOREIGN KEY (learning_programme_id) REFERENCES learning_programmes (id);