CREATE TABLE faculties
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title      VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_faculties PRIMARY KEY (id)
);

insert into faculties (title, created_at)
values ('Java', '2022-07-25 12:32:25.000000'),
       ('Python', '2022-07-25 12:32:51.000000');