CREATE TABLE lessons_template
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    theme              VARCHAR(255),
    duration           TIME WITHOUT TIME ZONE,
    training_manual    VARCHAR(255),
    homework           VARCHAR(255),
    course_template_id BIGINT,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    update_at          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_lessons_template PRIMARY KEY (id)
);

ALTER TABLE lessons_template
    ADD CONSTRAINT FK_LESSONS_TEMPLATE_ON_COURSE_TEMPLATE FOREIGN KEY (course_template_id) REFERENCES course_template (id);

insert into lessons_template ( theme, duration, course_template_id)
values  ('Java_Lesson', '00:45:00', 1),
        ('Python_Lesson', '00:30:00', 2);