CREATE TABLE active_lesson
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lesson_template_id BIGINT,
    theme              VARCHAR(255),
    learning_programm  BIGINT,
    started_at         date,
    finished_at        date,
    training_manual    VARCHAR(255),
    homework           VARCHAR(255),
    is_finished        BOOLEAN,
    created_at         TIMESTAMP WITHOUT TIME ZONE default current_timestamp,
    update_at          TIMESTAMP WITHOUT TIME ZONE default current_timestamp,
    CONSTRAINT pk_active_lesson PRIMARY KEY (id)
);

ALTER TABLE active_lesson
    ADD CONSTRAINT FK_ACTIVE_LESSON_ON_LEARNING_PROGRAMM FOREIGN KEY (learning_programm) REFERENCES course (id);

ALTER TABLE active_lesson
    ADD CONSTRAINT FK_ACTIVE_LESSON_ON_LESSON_TEMPLATE FOREIGN KEY (lesson_template_id) REFERENCES lessons_template (id);