CREATE TABLE course_template
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title      VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE default current_timestamp,
    update_at  TIMESTAMP WITHOUT TIME ZONE default current_timestamp,
    CONSTRAINT pk_course_template PRIMARY KEY (id)
);

insert into course_template (title, created_at)
values ('Java1', '2022-07-25 12:34:50.000000'),
       ('Python1', '2022-07-25 12:34:59.000000');
