CREATE TABLE learning_programmes
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title         VARCHAR(255),
    status        VARCHAR(255),
    create_at     TIMESTAMP WITHOUT TIME ZONE,
    deprecated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_learning_programmes PRIMARY KEY (id)
);