CREATE TABLE stream_template
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(255),
    facultity_id BIGINT,
    CONSTRAINT pk_stream_template PRIMARY KEY (id)
);

ALTER TABLE stream_template
    ADD CONSTRAINT FK_STREAM_TEMPLATE_ON_FACULTITY FOREIGN KEY (facultity_id) REFERENCES faculties (id);

insert into stream_template ( title, facultity_id)
values  ( 'Java_2022', 1),
        ( 'Python_2022', 2);