CREATE TABLE faculties
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(255),
    CONSTRAINT pk_faculties PRIMARY KEY (id)
);

create table faculties_group_learning_programme
(
    faculty_id            BIGINT not null
        constraint fk_faculties_group_learning_programme_on_faculties references faculties (id),
    group_id              BIGINT not null
        constraint fk_faculties_group_learning_programme_on_groups references groups (id),
    learning_programme_id BIGINT not null
        constraint fk_faculties_group_learning_programme_on_learning_programmes references learning_programmes (id)
);
insert into faculties (id, title)
values (1, 'Java'),
       (2, 'Python');

insert into faculties_group_learning_programme(faculty_id, group_id, learning_programme_id)
VALUES (1,1,1),
       (1,2,3),
       (2,3,3)