server:
  port: 5555

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://localhost:8181
#          Включить для сборки docker-compose
#          uri: http://core-service:8181
          predicates:
          - Path=/core/**
          filters:
            - StripPrefix=1
            - JwtAuthFilter

        - id: auth-service
          uri: http://localhost:8188
#          Включить для сборки docker-compose
#          uri: http://auth-service:8188
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/web-auth
            - JwtAuthFilter

jwt:
  secret: TXqgStgiwEc16r7M8csn55pFotV0tdp+TzzVATUVn5gTLhT8BAE9kpmc/vVvt3IiirL3lXtj8WA2darXR90Wmg==