export enum Authorities{
  ADMIN_USER_READ='ADMIN_USER_READ',
  ADMIN_USER_WRITE='ADMIN_USER_WRITE',
  ADMIN_USER_DELETE ='ADMIN_USER_DELETE',
  REGISTRATION_READ='REGISTRATION_READ',
  REGISTRATION_WRITE='REGISTRATION_WRITE'
}
